//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drones.CambioService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CambioService.TipoCambioServiceSoap")]
    public interface TipoCambioServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompra", ReplyAction="*")]
        double GetCompra();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetCompraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVenta", ReplyAction="*")]
        double GetVenta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetVentaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoCambioServiceSoapChannel : Drones.CambioService.TipoCambioServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoCambioServiceSoapClient : System.ServiceModel.ClientBase<Drones.CambioService.TipoCambioServiceSoap>, Drones.CambioService.TipoCambioServiceSoap {
        
        public TipoCambioServiceSoapClient() {
        }
        
        public TipoCambioServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoCambioServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetCompra() {
            return base.Channel.GetCompra();
        }
        
        public System.Threading.Tasks.Task<double> GetCompraAsync() {
            return base.Channel.GetCompraAsync();
        }
        
        public double GetVenta() {
            return base.Channel.GetVenta();
        }
        
        public System.Threading.Tasks.Task<double> GetVentaAsync() {
            return base.Channel.GetVentaAsync();
        }
    }
}
